[CELEBORN-1387] Allow more retries when requesting more memory in sortbasedpusher
### What changes were proposed in this pull request?

this PR proposes to have more retries when asking for more memory in SortBasedPusher to increase the success rate

### Why are the changes needed?

in prod, we have a few jobs suffer from the following exception when asking for more memory in sortbasedpusher,

```
 org.apache.spark.memory.SparkOutOfMemoryError: Unable to acquire 1073741824 bytes of memory, got 760427315
```

we can see that it cannot allocate 1G memory but can still get 700+MB which should be sufficient for handling more records, but still, it failed

we have used this change in our prod env, it successfully mitigate the issue

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

prod

Closes #2461 from CodingCat/oom_retry.

Authored-by: CodingCat <zhunansjtu@gmail.com>
Signed-off-by: zky.zhoukeyong <zky.zhoukeyong@alibaba-inc.com>