[CELEBORN-740] Remove usage of AccessController
### What changes were proposed in this pull request?

Remove usage of deprecated `java.security.AccessController`

### Why are the changes needed?

`AccessController` is deprecated for removal since Java 17

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/security/AccessController.html

Recover building for Java 17

```
[INFO] compiling 72 Scala sources and 209 Java sources to /home/runner/work/incubator-celeborn/incubator-celeborn/common/target/classes ...
Error:  /home/runner/work/incubator-celeborn/incubator-celeborn/common/src/main/scala/org/apache/celeborn/common/serializer/SerializationDebugger.scala:71: class AccessController in package security is deprecated
Error: [ERROR] one error found
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

```
scala> System.getProperty("java.version")
res0: String = 1.8.0_332

scala> System.getProperty("sun.io.serialization.extendedDebugInfo")
res1: String = null

scala> java.lang.Boolean.getBoolean("sun.io.serialization.extendedDebugInfo")
res2: Boolean = false
```

Closes #1652 from pan3793/CELEBORN-740.

Authored-by: Cheng Pan <chengpan@apache.org>
Signed-off-by: zky.zhoukeyong <zky.zhoukeyong@alibaba-inc.com>
(cherry picked from commit c33aabfa37dc876d03132e53e29d3c1c0063719d)
Signed-off-by: zky.zhoukeyong <zky.zhoukeyong@alibaba-inc.com>