[CELEBORN-1084][FOLLOWUP][0.3] Import `mock` method to recover CI
### What changes were proposed in this pull request?

As title

### Why are the changes needed?

The branch-0.3 CI process encountered a compiler error as follows:

```
Error:  /home/runner/work/incubator-celeborn/incubator-celeborn/worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/FileWriterSuiteJ.java:140:65:  error: cannot find symbol
Warning:  javac exited with exit code 1
```

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Pass GA

Closes #2040 from cfmcgrady/celeborn-1084-0.3-followup.

Authored-by: Fu Chen <cfmcgrady@gmail.com>
Signed-off-by: Fu Chen <cfmcgrady@gmail.com>