[CELEBORN-674] Support revive for empty locations
### What changes were proposed in this pull request?
If some task retry or scheduled by speculation, the executors will keep failing because revive does not support old partition is empty.
Celeborn will trigger stage end if all mapper task calls mapper end, this is not what spark thinks a stage ends.  So in this moment, kill spark executors will cause the spark task to rerun the current stage. Shuffle client will need to register shuffle first but get empty partition locations, and it will need to revive to get the latest location with empty locations.

Here are logs example

```
23/06/13 08:32:11 ERROR ShuffleClientImpl: Exception raised while reviving for shuffle 12 map 970 attempt 27 partition 152 epoch -1.
java.lang.NullPointerException
	at org.apache.celeborn.common.util.PbSerDeUtils$.toPbPartitionLocation(PbSerDeUtils.scala:258)
	at org.apache.celeborn.common.protocol.message.ControlMessages$Revive$.apply(ControlMessages.scala:207)
	at org.apache.celeborn.client.ShuffleClientImpl.revive(ShuffleClientImpl.java:573)
	at org.apache.celeborn.client.ShuffleClientImpl.pushOrMergeData(ShuffleClientImpl.java:656)
	at org.apache.celeborn.client.ShuffleClientImpl.pushData(ShuffleClientImpl.java:984)
	at org.apache.celeborn.client.write.DataPusher.pushData(DataPusher.java:197)
	at org.apache.celeborn.client.write.DataPusher.access$500(DataPusher.java:38)
	at org.apache.celeborn.client.write.DataPusher$1.run(DataPusher.java:123)
23/06/13 08:32:11 ERROR Executor: Exception in task 21.27 in stage 54.1 (TID 17255)
org.apache.celeborn.common.exception.CelebornIOException: Revive for shuffle spark-3df9647407f14c39868a17b7950899c5-12 partition 152 failed.
	at org.apache.celeborn.client.ShuffleClientImpl.pushOrMergeData(ShuffleClientImpl.java:666)
	at org.apache.celeborn.client.ShuffleClientImpl.pushData(ShuffleClientImpl.java:984)
	at org.apache.celeborn.client.write.DataPusher.pushData(DataPusher.java:197)
	at org.apache.celeborn.client.write.DataPusher.access$500(DataPusher.java:38)
	at org.apache.celeborn.client.write.DataPusher$1.run(DataPusher.java:123)
23/06/13 08:32:11 INFO CoarseGrainedExecutorBackend: Got assigned task 17309
```

### Why are the changes needed?
To make shuffle client able to revive with empty locations.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
K8S cluster.

Closes #1586 from FMX/CELEBORN-674.

Authored-by: Ethan Feng <ethanfeng@apache.org>
Signed-off-by: zky.zhoukeyong <zky.zhoukeyong@alibaba-inc.com>