[CELEBORN-981] Imrpove enable graceful shutdown tips
### What changes were proposed in this pull request?

```
celeborn.worker.graceful.shutdown.enabled=true
```

```
  23/09/15 17:17:29,887 ERROR [main] Worker: Initialize worker failed.
  java.lang.AssertionError: assertion failed: If enable graceful shutdown, the worker should use stable server port.
  	at scala.Predef$.assert(Predef.scala:223)
  	at org.apache.celeborn.service.deploy.worker.Worker.<init>(Worker.scala:87)
  	at org.apache.celeborn.service.deploy.worker.Worker$.main(Worker.scala:734)
  	at org.apache.celeborn.service.deploy.worker.Worker.main(Worker.scala)
```

```
23/09/15 17:51:25,937 ERROR [main] Worker: Initialize worker failed.
  java.lang.AssertionError: assertion failed: If enable graceful shutdown, the worker should use non-zero port. celeborn.worker.rpc.port=0, celeborn.worker.fetch.port=9193, celeborn.worker.push.port=9192, celeborn.worker.replicate.port=9194
  	at scala.Predef$.assert(Predef.scala:223)
  	at org.apache.celeborn.service.deploy.worker.Worker.<init>(Worker.scala:91)
  	at org.apache.celeborn.service.deploy.worker.Worker$.main(Worker.scala:738)
  	at org.apache.celeborn.service.deploy.worker.Worker.main(Worker.scala)
```

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

Closes #1917 from cxzl25/CELEBORN-981.

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: zky.zhoukeyong <zky.zhoukeyong@alibaba-inc.com>