[CELEBORN-1397] Fix compilation error on branch-0.4
### What changes were proposed in this pull request?
Fix MasterClient construct method use in MasterClientSuiteJ.

### Why are the changes needed?
MasterClient's construct method has changed by https://github.com/apache/celeborn/pull/2281 on main. It's a feature to support authentication on branch-0.5.

https://github.com/apache/celeborn/pull/2466 's backport on branch-0.4 here caused a conflict in MasterClientSuiteJ.java:319.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Local compile test.

Closes #2475 from onebox-li/branch-0.4-fix-compile.

Authored-by: onebox-li <lyh-36@163.com>
Signed-off-by: SteNicholas <programgeek@163.com>