[CELEBORN-2142][FOLLOWUP][0.6] Fix failure of compilation
### What changes were proposed in this pull request?

### Why are the changes needed?

https://github.com/apache/celeborn/actions/runs/18090291003/job/51469133996

> Error:  /home/runner/work/celeborn/celeborn/worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StoragePolicy.scala:148: value getStorageType is not a member of org.apache.celeborn.common.meta.DiskFileInfo
Error:  /home/runner/work/celeborn/celeborn/worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StoragePolicy.scala:160: value getStorageType is not a member of org.apache.celeborn.common.meta.DiskFileInfo

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

Closes #3493 from cxzl25/CELEBORN-2142_f.

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: SteNicholas <programgeek@163.com>