[CELEBORN-1461] Fix Celeborn ipv6 local hostname resolution
### What changes were proposed in this pull request?
Fix ipv6 hostname resolution to have `[]` around the ipv6 address.

### Why are the changes needed?
Previously was getting error:
```
java.lang.AssertionError: assertion failed: Expected hostname or IPv6 IP enclosed in [] but got <ipv6 address>
  	at scala.Predef$.assert(Predef.scala:223)
  	at org.apache.celeborn.common.util.Utils$.checkHost(Utils.scala:429)
  	at org.apache.celeborn.service.deploy.worker.Worker.<init>(Worker.scala:136)
  	at org.apache.celeborn.service.deploy.worker.Worker$.main(Worker.scala:953)
  	at org.apache.celeborn.service.deploy.worker.Worker.main(Worker.scala)
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
started the worker and the service starts up now and binds to ipv6 address

Closes #2564 from akpatnam25/CELEBORN-1461.

Authored-by: Aravind Patnam <apatnam@linkedin.com>
Signed-off-by: mingji <fengmingxiao.fmx@alibaba-inc.com>
(cherry picked from commit cff2a7daa023b8be40edd726bf63a2de6e578cda)
Signed-off-by: mingji <fengmingxiao.fmx@alibaba-inc.com>