[CELEBORN-1747] Fix flaky test - HybridShuffleWordCountTest
### What changes were proposed in this pull request?
Use `setupMiniClusterWithRandomPorts` instead of `setUpMiniCluster`, and set `setUpMiniCluster` to be private.

### Why are the changes needed?
Fix flaky test.
```
HybridShuffleWordCountTest:
Nov 26, 2024 4:44:10 AM org.glassfish.jersey.server.wadl.WadlFeature configure
WARNING: JAXBContext implementation could not be found. WADL feature is disabled.
*** RUN ABORTED ***
  java.io.IOException: Failed to bind to localhost/127.0.0.1:32886
  at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
  at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
  at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
  at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
  at org.apache.celeborn.server.common.http.HttpServer.start(HttpServer.scala:45)
  at org.apache.celeborn.server.common.HttpService.startInternal(HttpService.scala:354)
  at org.apache.celeborn.server.common.HttpService.startHttpServer(HttpService.scala:210)
  at org.apache.celeborn.service.deploy.MiniClusterFeature.createMaster(MiniClusterFeature.scala:115)
  at org.apache.celeborn.service.deploy.MiniClusterFeature.setUpMaster(MiniClusterFeature.scala:155)
  ...
  Cause: java.net.BindException: Address already in use

```

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
GA.

Closes #2950 from turboFei/fix_flaky_test.

Authored-by: Wang, Fei <fwang12@ebay.com>
Signed-off-by: SteNicholas <programgeek@163.com>