[CELEBORN-1570] Fix flaky test - monitor non-critical error metrics in DeviceMonitorSuite
### What changes were proposed in this pull request?

### Why are the changes needed?
https://github.com/apache/celeborn/actions/runs/10441850633/job/28913478820?pr=2692

```
- monitor non-critical error metrics *** FAILED ***
  java.lang.AssertionError: expected:<2> but was:<1>
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.failNotEquals(Assert.java:835)
  at org.junit.Assert.assertEquals(Assert.java:120)
  at org.junit.Assert.assertEquals(Assert.java:146)
  at org.apache.celeborn.service.deploy.worker.storage.DeviceMonitorSuite.$anonfun$new$22(DeviceMonitorSuite.scala:405)
```

Because calling `System.currentTimeMillis()` twice may get the same value. Gauge uses the size of the set, and the same value will be deduplicated.

https://github.com/apache/celeborn/blob/0ee3c3a4bdef3b97fca6be04f03ac36c2e12e1a6/worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/ObservedDevice.scala#L81-L91

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
GA

Closes #2694 from cxzl25/CELEBORN-1570.

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: SteNicholas <programgeek@163.com>
(cherry picked from commit 1f497cb92b9a4a78dba8d7b57d77c29ed5862db3)
Signed-off-by: SteNicholas <programgeek@163.com>