[CELEBORN-1720][FOLLOWUP] Fix compilation error of CelebornTezReader for ShuffleClient#readPartition
### What changes were proposed in this pull request?

Fix compilation error of `CelebornTezReader` for `ShuffleClient#readPartition`.

### Why are the changes needed?

There is a compilation error in `CelebornTezReader` for `ShuffleClient#readPartition`, which is as follows:

```
Error:  /home/runner/work/celeborn/celeborn/client-tez/tez/src/main/java/org/apache/celeborn/client/CelebornTezReader.java:57:21:  error: no suitable method found for readPartition(int,int,int,int,int,MetricsCallback)
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI.

Closes #3073 from SteNicholas/CELEBORN-1720.

Authored-by: SteNicholas <programgeek@163.com>
Signed-off-by: mingji <fengmingxiao.fmx@alibaba-inc.com>