[MINOR] Fix PbSerDeUtilsTest failure
### What changes were proposed in this pull request?

Fix PbSerDeUtilsTest failure for spark4 jobs

```
Error:  /home/runner/work/celeborn/celeborn/common/src/test/scala/org/apache/celeborn/common/util/PbSerDeUtilsTest.scala:851: comparing values of types Boolean and Boolean using `equals` unsafely bypasses cooperative equality; use `==` instead
Error: [ERROR] one error found
```
https://github.com/apache/celeborn/actions/runs/27126367363/job/80055898287?pr=3720

### Why are the changes needed?

After this change https://github.com/apache/celeborn/pull/3675, some of tests are failing.

### Does this PR resolve a correctness bug?

- [ ] Yes

### Does this PR introduce _any_ user-facing change?

- [ ] Yes

### How was this patch tested?

Existing UTs.

Closes #3722 from s0nskar/CELEBORN-1577_fix_test.

Authored-by: Sanskar Modi <sanskarmodi97@gmail.com>
Signed-off-by: Nicholas Jiang <programgeek@163.com>