[CELEBORN-2023] Spark4 Client incompatible with isLocalMaster method
### What changes were proposed in this pull request?

### Why are the changes needed?

```java
Exception in thread "main" java.lang.NoSuchMethodError: 'boolean org.apache.spark.util.Utils.isLocalMaster(org.apache.spark.SparkConf)'
	at org.apache.spark.shuffle.celeborn.SparkShuffleManager.executorCores(SparkShuffleManager.java:464)
	at org.apache.spark.shuffle.celeborn.SparkShuffleManager.<init>(SparkShuffleManager.java:117)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:75)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:53)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.spark.util.Utils$.instantiateSerializerOrShuffleManager(Utils.scala:2584)
	at org.apache.spark.shuffle.ShuffleManager$.create(ShuffleManager.scala:108)
	at org.apache.spark.SparkEnv.initializeShuffleManager(SparkEnv.scala:226)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:589)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:3055
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
local test

Closes #3305 from cxzl25/CELEBORN-2023.

Lead-authored-by: sychen <sychen@ctrip.com>
Co-authored-by: cxzl25 <3898450+cxzl25@users.noreply.github.com>
Signed-off-by: 子懿 <ziyi.jxf@antgroup.com>
(cherry picked from commit 7eee202b5572ff0d86a9fa0488bfaf41ceb9d34a)
Signed-off-by: 子懿 <ziyi.jxf@antgroup.com>